# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: app
# The size of the persistent disk of the application (in MB).
disk: 1024
# The runtime the application uses.
type: nodejs:12

variables:
    env:
        NODE_ENV: production

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
#relationships:
# database: "db:mysql"

build:
  flavor: none
# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
       npm -d install
       npm -d run build
       next build
# The configuration of app when it is exposed to the web.
web:
  commands:
   start: "next start"

dependencies:
  nodejs:
    next: "^9.2.1"
    "@ampproject/toolbox-optimizer": "1.1.1"
    "@babel/core": "7.7.2"
    "@babel/plugin-proposal-class-properties": "7.7.0"
    "@babel/plugin-proposal-nullish-coalescing-operator": "7.7.4"
    "@babel/plugin-proposal-object-rest-spread": "7.6.2"
    "@babel/plugin-proposal-optional-chaining": "7.7.4"
    "@babel/plugin-syntax-dynamic-import": "7.2.0"
    "@babel/plugin-transform-modules-commonjs": "7.7.0"
    "@babel/plugin-transform-runtime": "7.6.2"
    "@babel/preset-env": "7.7.1"
    "@babel/preset-modules": "0.1.1"
    "@babel/preset-react": "7.7.0"
    "@babel/preset-typescript": "7.7.2"
    "@babel/runtime": "7.7.2"
    "@babel/runtime-corejs2": "7.7.2"
    "amphtml-validator": "1.0.23"
    "async-retry": "1.2.3"
    "async-sema": "3.0.0"
    "autodll-webpack-plugin": "0.4.2"
    "babel-core": "7.0.0-bridge.0"
    "babel-loader": "8.0.6"
    "babel-plugin-syntax-jsx": "6.18.0"
    "babel-plugin-transform-define": "2.0.0"
    "babel-plugin-transform-react-remove-prop-types": "0.4.24"
    "browserslist": "4.8.3"
    "cache-loader": "4.1.0"
    "chalk": "2.4.2"
    "ci-info": "2.0.0"
    "compression": "1.7.4"
    "conf": "5.0.0"
    "content-type": "1.0.4"
    "cookie": "0.4.0"
    "css-loader": "3.3.0"
    "cssnano-simple": "1.0.0"
    "devalue": "2.0.1"
    "etag": "1.8.1"
    "file-loader": "4.2.0"
    "find-up": "4.0.0"
    "fork-ts-checker-webpack-plugin": "3.1.1"
    "fresh": "0.5.2"
    "gzip-size": "5.1.1"
    "ignore-loader": "0.1.2"
    "is-docker": "2.0.0"
    "is-wsl": "2.1.1"
    "jest-worker": "24.9.0"
    "json5": "2.1.1"
    "launch-editor": "2.2.1"
    "loader-utils": "1.2.3"
    "lodash.curry": "4.1.1"
    "lru-cache": "5.1.1"
    "mini-css-extract-plugin": "0.8.0"
    "mkdirp": "0.5.1"
    "node-fetch": "2.6.0"
    "object-assign": "4.1.1"
    "ora": "3.4.0"
    "path-to-regexp": "6.1.0"
    "pnp-webpack-plugin": "1.5.0"
    "postcss-flexbugs-fixes": "4.1.0"
    "postcss-loader": "3.0.0"
    "postcss-preset-env": "6.7.0"
    "prop-types": "15.7.2"
    "prop-types-exact": "1.2.0"
    "raw-body": "2.4.0"
    "react-error-overlay": "5.1.6"
    "react-is": "16.8.6"
    "recast": "0.18.5"
    "resolve-url-loader": "3.1.1"
    "sass-loader": "8.0.2"
    "send": "0.17.1"
    "source-map": "0.6.1"
    "string-hash": "1.1.3"
    "strip-ansi": "5.2.0"
    "style-loader": "1.0.0"
    "styled-jsx": "3.2.4"
    "terser": "4.4.2"
    "thread-loader": "2.1.3"
    "unfetch": "4.1.0"
    "url": "0.11.0"
    "url-polyfill": "1.1.7"
    "use-subscription": "1.1.1"
    "watchpack": "2.0.0-beta.5"
    "webpack": "4.41.2"
    "webpack-dev-middleware": "3.7.0"
    "webpack-hot-middleware": "2.25.0"
    "webpack-sources": "1.4.3"
    "whatwg-fetch": "3.0.0"

mounts:
    'run':
        source: local
        source_path: run